---
# MiddlewareTCP for IP Whitelisting
apiVersion: traefik.io/v1alpha1
kind: MiddlewareTCP
metadata:
  name: tcp-ipwhitelist
  namespace: microservices
spec:
  ipWhiteList:
    sourceRange:
      - 10.0.0.0/8
      - 192.168.0.0/16
      - 172.16.0.0/12

---
# MiddlewareTCP for IP Allow List with specific IPs
apiVersion: traefik.io/v1alpha1
kind: MiddlewareTCP
metadata:
  name: tcp-allowlist-specific
  namespace: microservices
spec:
  ipAllowList:
    sourceRange:
      - 192.168.1.100
      - 192.168.1.101
      - 192.168.1.102

---
# MiddlewareTCP for InFlightConn (Connection Limiting)
apiVersion: traefik.io/v1alpha1
kind: MiddlewareTCP
metadata:
  name: tcp-inflightconn
  namespace: microservices
spec:
  inFlightConn:
    amount: 100

---
# MiddlewareTCP combining IP whitelist and connection limit
apiVersion: traefik.io/v1alpha1
kind: MiddlewareTCP
metadata:
  name: tcp-combined-security
  namespace: microservices
spec:
  ipWhiteList:
    sourceRange:
      - 10.0.0.0/8
      - 192.168.0.0/16

---
# MiddlewareTCP for rate limiting connections
apiVersion: traefik.io/v1alpha1
kind: MiddlewareTCP
metadata:
  name: tcp-ratelimit
  namespace: microservices
spec:
  inFlightConn:
    amount: 50

---
# MiddlewareTCP for production IP whitelist
apiVersion: traefik.io/v1alpha1
kind: MiddlewareTCP
metadata:
  name: tcp-prod-whitelist
  namespace: microservices
  labels:
    environment: production
spec:
  ipWhiteList:
    sourceRange:
      - 10.10.0.0/16
      - 172.20.0.0/16