---
# TLSOption for default namespace
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: default-tls-12
  namespace: default
spec:
  minVersion: VersionTLS12
  maxVersion: VersionTLS13
  cipherSuites:
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
  curvePreferences:
    - CurveP521
    - CurveP384
  sniStrict: false

---
# TLSOption for microservices namespace with strict TLS 1.3
apiVersion: v1
kind: Namespace
metadata:
  name: microservices
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: strict-tls-13
  namespace: microservices
spec:
  minVersion: VersionTLS13
  maxVersion: VersionTLS13
  sniStrict: true
  alpnProtocols:
    - h2
    - http/1.1

---
# Another TLSOption in microservices for modern browsers
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: modern-browsers
  namespace: microservices
spec:
  minVersion: VersionTLS12
  maxVersion: VersionTLS13
  cipherSuites:
    - TLS_AES_128_GCM_SHA256
    - TLS_AES_256_GCM_SHA384
    - TLS_CHACHA20_POLY1305_SHA256
  curvePreferences:
    - X25519
    - CurveP256
  sniStrict: false
  clientAuth:
    clientAuthType: NoClientCert

---
# TLSOption for production namespace
apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: production-tls
  namespace: production
spec:
  minVersion: VersionTLS12
  maxVersion: VersionTLS13
  sniStrict: true
  preferServerCipherSuites: true
  clientAuth:
    clientAuthType: RequestClientCert

---
# TLSOption for staging namespace
apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: staging-tls
  namespace: staging
spec:
  minVersion: VersionTLS11
  maxVersion: VersionTLS13
  sniStrict: false
  
---
# TLSOption with mTLS in microservices
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: mtls-required
  namespace: microservices
spec:
  minVersion: VersionTLS12
  clientAuth:
    clientAuthType: RequireAndVerifyClientCert
    secretNames:
      - client-ca-cert

---
# Legacy TLSOption for backwards compatibility
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: legacy-support
  namespace: default
spec:
  minVersion: VersionTLS10
  maxVersion: VersionTLS12
  sniStrict: false
  cipherSuites:
    - TLS_RSA_WITH_AES_128_CBC_SHA
    - TLS_RSA_WITH_AES_256_CBC_SHA